"""employees_status

Revision ID: 59a3f9bc7288
Revises: 3612a8cbbfbb
Create Date: 2019-08-11 15:40:56.094267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59a3f9bc7288'
down_revision = '3612a8cbbfbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('status', sa.VARCHAR(length=100), nullable=True))
    op.create_unique_constraint(None, 'employees_skills', ['id'])
    op.create_unique_constraint(None, 'skills', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skills', type_='unique')
    op.drop_constraint(None, 'employees_skills', type_='unique')
    op.drop_column('employees', 'status')
    # ### end Alembic commands ###
