"""employee_departments_new_table

Revision ID: e88e5206d7f3
Revises: 38a2ece4c51d
Create Date: 2019-07-05 21:14:46.769467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e88e5206d7f3'
down_revision = '38a2ece4c51d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_employee_departments_department_id'), 'employee_departments', ['department_id'], unique=False)
    op.create_index(op.f('ix_employee_departments_employee_id'), 'employee_departments', ['employee_id'], unique=False)
    op.create_unique_constraint(None, 'cadre_movements', ['id'])
    op.create_unique_constraint(None, 'departments', ['id'])
    op.drop_index('ix_employees_department_id', table_name='employees')
    op.create_unique_constraint(None, 'employees', ['id'])
    op.drop_constraint('employees_department_id_fkey', 'employees', type_='foreignkey')
    op.drop_column('employees', 'department_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('employees_department_id_fkey', 'employees', 'departments', ['department_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'employees', type_='unique')
    op.create_index('ix_employees_department_id', 'employees', ['department_id'], unique=False)
    op.drop_constraint(None, 'departments', type_='unique')
    op.drop_constraint(None, 'cadre_movements', type_='unique')
    op.drop_index(op.f('ix_employee_departments_employee_id'), table_name='employee_departments')
    op.drop_index(op.f('ix_employee_departments_department_id'), table_name='employee_departments')
    op.drop_table('employee_departments')
    # ### end Alembic commands ###
